"""Central configuration for reproducible research runs."""

DEFAULT_N_FACTORS = 5
DEFAULT_ANNUALIZATION_FACTOR = 252
DEFAULT_MOMENTUM_WINDOW = 252
DEFAULT_REVERSAL_WINDOW = 5
DEFAULT_OVERNIGHT_WINDOW = 5
